"""NVDA's spoken labels for roles and states. GENERATED — do not edit by hand.

Regenerate with `python3 scripts/generate_labels.py`. Derived from NVDA
(source/controlTypes/{role,state}.py), GPL-2.0-or-later; see this package's LICENSE.

These strings ARE the product's vocabulary: every announcement this package composes is built
from them, so a wrong one is a wrong finding that reads perfectly.
"""

ROLE_LABELS: dict[str, str] = {
    "ALERT": 'alert',
    "ALIGNMENT": 'alignment',
    "ANIMATION": 'animation',
    "APPLICATION": 'application',
    "ARTICLE": 'article',
    "AUDIO": 'audio',
    "BGCOLOR": 'background color',
    "BLOCKQUOTE": 'block quote',
    "BOLD": 'bold',
    "BORDER": 'border',
    "BOX": 'box',
    "BUSY_INDICATOR": 'busy indicator',
    "BUTTON": 'button',
    "CALENDAR": 'calendar',
    "CANVAS": 'canvas',
    "CAPTION": 'caption',
    "CARET": 'caret',
    "CHARACTER": 'character',
    "CHART": 'chart',
    "CHARTELEMENT": 'chart element',
    "CHECKBOX": 'check box',
    "CHECKMENUITEM": 'check menu item',
    "CLOCK": 'clock',
    "COLORCHOOSER": 'color chooser',
    "COMBOBOX": 'combo box',
    "COMMENT": 'comment',
    "CURSOR": 'cursor',
    "DATAGRID": 'data grid',
    "DATAITEM": 'data item',
    "DATEEDITOR": 'date edit',
    "DEFINITION": 'definition',
    "DELETED_CONTENT": 'deleted',
    "DESKTOPICON": 'desktop icon',
    "DESKTOPPANE": 'desktop pane',
    "DIAGRAM": 'diagram',
    "DIAL": 'dial',
    "DIALOG": 'dialog',
    "DIRECTORYPANE": 'directory pane',
    "DOCUMENT": 'document',
    "DROPDOWNBUTTON": 'drop down button',
    "DROPDOWNBUTTONGRID": 'drop down button grid',
    "DROPLIST": 'drop list',
    "EDITABLETEXT": 'edit',
    "EDITBAR": 'edit bar',
    "EMBEDDEDOBJECT": 'embedded object',
    "ENDNOTE": 'end note',
    "FGCOLOR": 'foreground color',
    "FIGURE": 'figure',
    "FILECHOOSER": 'file chooser',
    "FILLER": 'filler',
    "FONTCHOOSER": 'font chooser',
    "FONTNAME": 'font name',
    "FONTSIZE": 'font size',
    "FOOTER": 'footer',
    "FOOTNOTE": 'foot note',
    "FORM": 'form',
    "FRAME": 'frame',
    "GLASSPANE": 'glass pane',
    "GRAPHIC": 'graphic',
    "GRIP": 'grip',
    "GROUPING": 'grouping',
    "HEADER": 'header',
    "HEADERITEM": 'header item',
    "HEADING": 'heading',
    "HEADING1": 'heading 1',
    "HEADING2": 'heading 2',
    "HEADING3": 'heading 3',
    "HEADING4": 'heading 4',
    "HEADING5": 'heading 5',
    "HEADING6": 'heading 6',
    "HELPBALLOON": 'help balloon',
    "HOTKEYFIELD": 'hot key field',
    "ICON": 'icon',
    "IMAGEMAP": 'image map',
    "INDENT": 'indent',
    "INDICATOR": 'indicator',
    "INPUTWINDOW": 'input window',
    "INSERTED_CONTENT": 'inserted',
    "INTERNALFRAME": 'frame',
    "IPADDRESS": 'IP address',
    "ITALIC": 'italic',
    "LABEL": 'label',
    "LANDMARK": 'landmark',
    "LAYEREDPANE": 'layered pane',
    "LINE": 'line',
    "LINK": 'link',
    "LIST": 'list',
    "LISTITEM": 'list item',
    "MARKED_CONTENT": 'highlighted',
    "MATH": 'math',
    "MENU": 'menu',
    "MENUBAR": 'menu bar',
    "MENUBUTTON": 'menu button',
    "MENUITEM": 'menu item',
    "NOTE": 'note',
    "OPTIONPANE": 'option pane',
    "PAGE": 'page',
    "PANE": 'pane',
    "PANEL": 'panel',
    "PARAGRAPH": 'paragraph',
    "PASSWORDEDIT": 'password edit',
    "POPUPMENU": 'menu',
    "PROGRESSBAR": 'progress bar',
    "PROPERTYPAGE": 'property page',
    "RADIOBUTTON": 'radio button',
    "RADIOMENUITEM": 'radio menu item',
    "REDUNDANTOBJECT": 'redundant object',
    "REGION": 'region',
    "RICHEDIT": 'rich edit',
    "ROOTPANE": 'root pane',
    "RULER": 'ruler',
    "SCROLLBAR": 'scroll bar',
    "SCROLLPANE": 'scroll pane',
    "SECTION": 'section',
    "SEPARATOR": 'separator',
    "SHAPE": 'shape',
    "SLIDER": 'slider',
    "SOUND": 'sound',
    "SPINBUTTON": 'spin button',
    "SPLITBUTTON": 'split button',
    "SPLITPANE": 'split pane',
    "STATICTEXT": 'text',
    "STATUSBAR": 'status bar',
    "STYLE": 'style',
    "SUBSCRIPT": 'subscript',
    "SUGGESTION": 'suggestion',
    "SUPERSCRIPT": 'superscript',
    "SWITCH": 'switch',
    "TAB": 'tab',
    "TABCONTROL": 'tab control',
    "TABLE": 'table',
    "TABLEBODY": 'table body',
    "TABLECELL": 'cell',
    "TABLECOLUMN": 'column',
    "TABLECOLUMNHEADER": 'column header',
    "TABLEFOOTER": 'table footer',
    "TABLEHEADER": 'table header',
    "TABLEROW": 'row',
    "TABLEROWHEADER": 'row header',
    "TEAROFFMENU": 'tear off menu',
    "TERMINAL": 'terminal',
    "TEXTFRAME": 'text frame',
    "THUMB": 'thumb control',
    "TITLEBAR": 'title bar',
    "TOGGLEBUTTON": 'toggle button',
    "TOOLBAR": 'tool bar',
    "TOOLTIP": 'tool tip',
    "TREEVIEW": 'tree view',
    "TREEVIEWBUTTON": 'tree view button',
    "TREEVIEWITEM": 'tree view item',
    "UNDERLINE": 'underline',
    "UNKNOWN": 'unknown',
    "VIDEO": 'video',
    "VIEWPORT": 'view port',
    "WHITESPACE": 'white space',
    "WINDOW": 'window',
}

STATE_LABELS: dict[str, str] = {
    "AUTOCOMPLETE": 'has auto complete',
    "BUSY": 'busy',
    "CHECKABLE": 'checkable',
    "CHECKED": 'checked',
    "CLICKABLE": 'clickable',
    "COLLAPSED": 'collapsed',
    "CROPPED": 'cropped',
    "DEFUNCT": 'defunct',
    "DRAGGABLE": 'draggable',
    "DRAGGING": 'dragging',
    "DROPTARGET": 'drop target',
    "EDITABLE": 'editable',
    "EXPANDED": 'expanded',
    "FOCUSABLE": 'focusable',
    "FOCUSED": 'focused',
    "HALFCHECKED": 'half checked',
    "HALF_PRESSED": 'half pressed',
    "HASCOMMENT": 'has comment',
    "HASFORMULA": 'has formula',
    "HASLONGDESC": 'has long description',
    "HASNOTE": 'has note',
    "HASPOPUP": 'subMenu',
    "HASPOPUP_DIALOG": 'opens dialog',
    "HASPOPUP_GRID": 'opens grid',
    "HASPOPUP_LIST": 'opens list',
    "HASPOPUP_TREE": 'opens tree',
    "ICONIFIED": 'iconified',
    "INTERNAL_LINK": 'same page',
    "INVALID_ENTRY": 'invalid entry',
    "INVISIBLE": 'invisible',
    "LINKED": 'linked',
    "MODAL": 'modal',
    "MULTILINE": 'multi line',
    "MULTISELECTABLE": 'multi-select',
    "OBSCURED": 'obscured',
    "OFFSCREEN": 'off screen',
    "ON": 'on',
    "OVERFLOWING": 'overflowing',
    "PINNED": 'pinned',
    "PRESSED": 'pressed',
    "PROTECTED": 'protected',
    "READONLY": 'read only',
    "REQUIRED": 'required',
    "SELECTABLE": 'selectable',
    "SELECTED": 'selected',
    "SORTED": 'sorted',
    "SORTED_ASCENDING": 'sorted ascending',
    "SORTED_DESCENDING": 'sorted descending',
    "UNAVAILABLE": 'unavailable',
    "UNLOCKED": 'unlocked',
    "VISITED": 'visited',
}

NEGATIVE_STATE_LABELS: dict[str, str] = {
    "CHECKED": 'not checked',
    "DROPTARGET": 'done dragging',
    "ON": 'off',
    "PRESSED": 'not pressed',
    "SELECTED": 'not selected',
}
